### ISSUE TITLE
selection highlight problem

### ISSUE THREAD

**Issue by zhiiwg** [asantos3/viriato#1]
Like this theme very much, thanks for your work :)

Just a little problem, when using viriato with One Dark(Atom's default UI theme), the selection of code is not easily to recognize. 

![qq 20160115224108](https://cloud.githubusercontent.com/assets/4954007/12355656/17769876-bbd9-11e5-9a4a-1e9140f004c6.png)

For example, the selection above is `Still,`, maybe selection border or something like `#323232` will be helpful.

**Comment by asantos3** [comment]
On the last few months I haven't been able to work on this theme so thanks for your support and reporting this :)

I need to check a few things but how do you think about changing the background and selection colors to One Dark but keeping the current syntax colors? Do you prefer the current black background?

**Comment by zhiiwg** [comment]
Actually I like current syntax colors very much, the vivid colors is why I like it, so I am happy to see keep it unchanged.

Oh, I think the current black background is good, but changing the background and selection colors to One Dark but keeping the current syntax colors will be a good choice too. When there is many default texts, for example, a markdown file's main part is plain text, the white text and black background, their contrast is too... mmm...eye-catcher? In this situation, White plain text on black background maybe too stand out. Of course, this problem is not so important in code highlight.

This is my opinion, the final decision is still up to you :+1:

**Comment by asantos3** [comment]
Just published 0.12.0, what do you think? Too bright or still too dark?

**Comment by zhiiwg** [comment]
:+1: better than black background, looks comfortable
